import type { GoalId, HousingStatus, LifeTask, VaultDocument } from './types';

export const colors = {
  ink: '#17131F',
  muted: '#6E6878',
  primary: '#6C4DFF',
  primaryDark: '#4C33D8',
  primarySoft: '#EEE9FF',
  lime: '#C9F36A',
  peach: '#FFD8C7',
  sky: '#CFEAFF',
  surface: '#FFFFFF',
  canvas: '#F8F6FF',
  line: '#E8E3EF',
  success: '#247B52',
  warning: '#A45B00',
  danger: '#B93838',
};

export const housingOptions: { id: HousingStatus; label: string; caption: string; emoji: string }[] = [
  { id: 'parents', label: 'Chez mes parents', caption: 'Je prépare mon départ', emoji: '🏠' },
  { id: 'searching', label: 'Je cherche', caption: 'Premier appart ou coloc', emoji: '🔎' },
  { id: 'tenant', label: 'Déjà en location', caption: 'Je veux tout mettre au carré', emoji: '🔑' },
  { id: 'residence', label: 'En résidence', caption: 'Crous, foyer ou résidence privée', emoji: '🏢' },
];

export const flagOptions = [
  { id: 'boursier', label: 'Je suis boursier·e' },
  { id: 'international', label: 'Étudiant·e international·e' },
  { id: 'revenu', label: "J'ai un revenu étudiant" },
  { id: 'sans-garant', label: "Je n'ai pas de garant" },
  { id: 'premiere-declaration', label: "Je n'ai jamais déclaré mes impôts" },
];

export const goalOptions: { id: GoalId; label: string; caption: string; emoji: string }[] = [
  { id: 'housing', label: 'Trouver mon appart', caption: 'Budget, dossier, garant et bail', emoji: '🛋️' },
  { id: 'benefits', label: 'Faire le point sur mes aides', caption: 'Savoir où vérifier et quoi préparer', emoji: '💸' },
  { id: 'documents', label: 'Mettre mes papiers au carré', caption: 'Savoir quoi garder et retrouver vite', emoji: '📁' },
  { id: 'health', label: 'Comprendre santé et impôts', caption: 'Ameli, mutuelle, première déclaration', emoji: '🩺' },
  { id: 'moving', label: 'Préparer mon départ', caption: 'Toutes les démarches dans le bon ordre', emoji: '📦' },
];

export const lifeTasks: LifeTask[] = [
  {
    id: 'housing-budget',
    title: 'Calcule ton vrai budget logement',
    subtitle: "Ne te fie pas qu'au montant du loyer.",
    category: 'Logement',
    duration: '4 min',
    timing: 'Avant de contacter des propriétaires',
    priority: 'urgent',
    why: "Un logement implique aussi les charges, l'assurance, l'énergie, internet, le dépôt et parfois les transports.",
    documents: ['Revenus mensuels', 'Aides déjà connues', 'Dépenses fixes'],
    steps: [
      'Indique ce que tu reçois chaque mois.',
      'Ajoute tes dépenses fixes et ton budget de vie.',
      'Garde une marge pour les dépenses imprévues.',
      'Utilise le résultat comme plafond de recherche.',
    ],
    sourceLabel: 'ANIL — budget logement',
    sourceUrl: 'https://www.anil.org/',
  },
  {
    id: 'visale',
    title: 'Vérifie Visale avant de signer',
    subtitle: 'Une garantie gratuite peut remplacer un garant classique.',
    category: 'Logement',
    duration: '12 min',
    timing: 'Avant la signature du bail',
    priority: 'urgent',
    why: "Le visa doit être obtenu suffisamment tôt pour être présenté au bailleur avant la mise en place du contrat de cautionnement.",
    documents: ["Pièce d'identité", 'Justificatif de situation', 'Informations sur les ressources'],
    steps: [
      'Vérifie ton éligibilité sur le site officiel.',
      'Crée ton espace et dépose les justificatifs demandés.',
      'Télécharge le visa une fois validé.',
      'Transmets-le au bailleur avant la signature du bail.',
    ],
    sourceLabel: 'Visale — site officiel',
    sourceUrl: 'https://www.visale.fr/',
  },
  {
    id: 'rental-file',
    title: 'Prépare un dossier locatif propre',
    subtitle: 'Un dossier complet évite les allers-retours.',
    category: 'Documents',
    duration: '15 min',
    timing: 'Avant les premières visites',
    priority: 'soon',
    why: "Un dossier organisé permet de candidater rapidement tout en évitant d'envoyer des informations inutiles ou sensibles.",
    documents: ["Pièce d'identité", 'Certificat de scolarité', 'Justificatifs de ressources', 'Documents du garant'],
    steps: [
      'Réunis les pièces utiles dans ton coffre.',
      'Masque les informations qui ne sont pas nécessaires.',
      'Fais vérifier le dossier par DossierFacile.',
      'N’envoie jamais de paiement avant une visite et un cadre clair.',
    ],
    sourceLabel: 'DossierFacile — service public',
    sourceUrl: 'https://www.dossierfacile.logement.gouv.fr/',
  },
  {
    id: 'benefits-check',
    title: 'Vérifie les aides qui te concernent',
    subtitle: "TutoVie t'oriente, le simulateur officiel confirme.",
    category: 'Aides',
    duration: '10 min',
    timing: "Dès qu'une situation change",
    priority: 'soon',
    why: "Le montant et l'éligibilité dépendent de nombreux paramètres. La bonne pratique consiste à utiliser une source officielle puis à suivre la démarche.",
    documents: ['Ressources', 'Situation familiale', 'Adresse et logement', 'Statut étudiant'],
    steps: [
      'Prépare les informations sur ta situation.',
      'Lance le simulateur officiel Mes droits sociaux.',
      'Note les aides à vérifier auprès de chaque organisme.',
      'Ajoute les démarches retenues à ta roadmap.',
    ],
    sourceLabel: 'Mes droits sociaux — simulateur officiel',
    sourceUrl: 'https://www.mesdroitssociaux.gouv.fr/',
  },
  {
    id: 'housing-aid',
    title: "Prépare ta demande d'aide au logement",
    subtitle: 'À faire une fois le bail signé et les clés récupérées.',
    category: 'Aides',
    duration: '15 min',
    timing: "Après l'entrée dans le logement",
    priority: 'later',
    why: "La demande nécessite des informations précises sur le logement, le bailleur et le compte bancaire du demandeur.",
    documents: ['Bail', 'RIB', 'Coordonnées du bailleur', 'Montant du loyer'],
    steps: [
      'Crée ou ouvre ton compte CAF.',
      'Renseigne les informations exactes du bail.',
      'Ajoute le RIB et les justificatifs demandés.',
      'Suis les messages et demandes complémentaires.',
    ],
    sourceLabel: 'CAF — aides au logement',
    sourceUrl: 'https://www.caf.fr/allocataires/aides-et-demarches/droits-et-prestations/logement',
  },
  {
    id: 'ameli',
    title: 'Vérifie ton espace Ameli',
    subtitle: 'Coordonnées, RIB, carte Vitale et médecin traitant.',
    category: 'Santé',
    duration: '8 min',
    timing: 'Au début de ton autonomie',
    priority: 'later',
    why: "Des coordonnées à jour facilitent les remboursements et les échanges avec l'Assurance Maladie.",
    documents: ['Carte Vitale', 'RIB', 'Adresse actuelle'],
    steps: [
      'Connecte-toi ou crée ton compte Ameli.',
      'Vérifie ton adresse et ton RIB.',
      'Contrôle les informations de ta carte Vitale.',
      'Repère tes contacts utiles en cas de problème.',
    ],
    sourceLabel: 'Assurance Maladie — Ameli',
    sourceUrl: 'https://www.ameli.fr/',
  },
  {
    id: 'first-tax',
    title: 'Anticipe ta première déclaration',
    subtitle: 'Comprendre rattachement, foyer fiscal et justificatifs.',
    category: 'Impôts',
    duration: '10 min',
    timing: 'Avant la prochaine campagne déclarative',
    priority: 'later',
    why: "La première déclaration est plus simple lorsqu'on sait à l'avance si l'on reste rattaché au foyer parental et où trouver les informations nécessaires.",
    documents: ['Numéro fiscal si disponible', 'Revenus de l’année', 'Adresse au 1er janvier'],
    steps: [
      'Clarifie ta situation de rattachement avec tes parents.',
      'Conserve les justificatifs de revenus.',
      'Vérifie ton adresse fiscale.',
      'Consulte la procédure officielle au moment de la campagne.',
    ],
    sourceLabel: 'Service-Public — première déclaration',
    sourceUrl: 'https://www.service-public.fr/particuliers/vosdroits/F369',
  },
];

export const vaultDocuments: VaultDocument[] = [
  { id: 'identity', label: "Pièce d'identité", hint: 'Recto-verso lisible', status: 'ready' },
  { id: 'school', label: 'Certificat de scolarité', hint: 'Année en cours', status: 'ready' },
  { id: 'rib', label: 'RIB à ton nom', hint: 'Souvent demandé par les organismes', status: 'missing' },
  { id: 'insurance', label: 'Assurance habitation', hint: 'À fournir pour le logement', status: 'missing' },
  { id: 'tax', label: "Avis d'imposition", hint: 'Le tien ou celui du foyer selon la situation', status: 'expires', expiresAt: 'À actualiser' },
];

export const assistantSuggestions = [
  "J'ai trouvé un appart, je fais quoi maintenant ?",
  "C'est quoi un avis d'imposition ?",
  "Je n'ai pas de garant, quelles options vérifier ?",
  "Quels papiers je dois garder ?",
];
