import type { DocumentItem, GoalId, HousingStatus, JourneyDefinition } from './types';

export const colors = {
  ink: '#17131F',
  muted: '#6E6878',
  primary: '#6C4DFF',
  primaryDark: '#4C33D8',
  primarySoft: '#EEE9FF',
  lavender: '#F4F0FF',
  lime: '#D7F58A',
  peach: '#FFD8C7',
  sky: '#CFEAFF',
  surface: '#FFFFFF',
  canvas: '#F7F6FB',
  line: '#E8E3EF',
  success: '#247B52',
  warning: '#A45B00',
  danger: '#B93838',
  dark: '#201A2B',
};

export const housingOptions: { id: HousingStatus; label: string; caption: string; emoji: string }[] = [
  { id: 'parents', label: 'Chez mes parents', caption: 'Je prépare mon départ', emoji: '🏠' },
  { id: 'searching', label: 'Je cherche un logement', caption: 'Premier appart ou coloc', emoji: '🔎' },
  { id: 'tenant', label: 'Déjà en location', caption: 'Je veux mettre mes démarches au clair', emoji: '🔑' },
  { id: 'residence', label: 'En résidence', caption: 'Crous, foyer ou résidence privée', emoji: '🏢' },
];

export const flagOptions = [
  { id: 'boursier', label: 'Je suis boursier·e' },
  { id: 'international', label: 'Je viens étudier en France' },
  { id: 'revenu', label: "J'ai un revenu étudiant" },
  { id: 'sans-garant', label: "Je n'ai pas de garant" },
  { id: 'premiere-declaration', label: "Je n'ai jamais déclaré mes impôts" },
  { id: 'deménagement', label: 'Je vais bientôt déménager' },
];

export const goalOptions: { id: GoalId; label: string; caption: string; emoji: string }[] = [
  { id: 'housing', label: 'Trouver mon premier logement', caption: 'Budget, dossier, recherche, bail et installation', emoji: '🛋️' },
  { id: 'benefits', label: 'Vérifier mes aides', caption: 'Comprendre quoi simuler, demander et suivre', emoji: '💶' },
  { id: 'documents', label: 'Mettre mes documents au clair', caption: 'Savoir quoi avoir, où le trouver et à quoi ça sert', emoji: '📁' },
  { id: 'health', label: 'Gérer ma santé administrative', caption: 'Ameli, carte Vitale, médecin et mutuelle', emoji: '🩺' },
  { id: 'taxes', label: 'Comprendre mes premiers impôts', caption: 'Rattachement, numéro fiscal et déclaration', emoji: '🧾' },
  { id: 'moving', label: 'Préparer un déménagement', caption: 'Préavis, contrats, adresses, état des lieux', emoji: '📦' },
];

export const documentCatalog: DocumentItem[] = [
  { id: 'identity', label: "Pièce d'identité", category: 'Identité', why: 'Elle sert à prouver ton identité dans presque toutes les démarches.', where: 'Carte nationale, passeport ou titre de séjour en cours de validité.', status: 'missing' },
  { id: 'school', label: 'Certificat de scolarité', category: 'Études', why: 'Il prouve ton statut étudiant pour le logement, les transports et certaines aides.', where: 'Dans ton ENT ou auprès de la scolarité.', status: 'missing' },
  { id: 'rib', label: 'RIB à ton nom', category: 'Banque', why: 'Les organismes en ont besoin pour verser des remboursements ou des aides.', where: 'Dans ton application bancaire ou auprès de ta banque.', status: 'missing' },
  { id: 'tax-notice', label: "Avis d'imposition", category: 'Impôts', why: 'Il est souvent demandé pour un logement ou une aide, même si tes revenus sont faibles.', where: 'Dans ton espace impots.gouv.fr ou auprès du foyer fiscal auquel tu es rattaché.', status: 'missing' },
  { id: 'lease', label: 'Bail ou contrat de résidence', category: 'Logement', why: 'Il prouve ton occupation du logement et contient les informations utiles à la CAF.', where: 'Remis par le bailleur ou la résidence au moment de la signature.', status: 'missing' },
  { id: 'insurance', label: "Attestation d'assurance habitation", category: 'Logement', why: 'Elle est généralement exigée pour récupérer les clés.', where: 'Téléchargeable après souscription auprès de ton assureur.', status: 'missing' },
  { id: 'vitale', label: 'Carte Vitale ou attestation de droits', category: 'Santé', why: 'Elle facilite les remboursements de soins.', where: 'Dans ton compte Ameli ou auprès de l’Assurance Maladie.', status: 'missing' },
  { id: 'resources', label: 'Justificatifs de ressources', category: 'Banque', why: 'Ils peuvent être demandés pour le logement, les aides ou un dossier administratif.', where: 'Fiches de paie, notification de bourse, attestation familiale ou relevé de prestations.', status: 'missing' },
];

export const journeys: JourneyDefinition[] = [
  {
    id: 'first-home',
    title: 'Mon premier logement',
    shortTitle: 'Premier logement',
    subtitle: 'Du budget jusqu’à l’installation, sans oublier les étapes entre les deux.',
    icon: '🏠',
    outcome: 'À la fin, tu auras un budget réaliste, un dossier prêt et une checklist complète jusqu’à la demande d’aide au logement.',
    estimatedTime: '25 à 40 min au total',
    recommendedFor: ['housing'],
    steps: [
      {
        id: 'home-intro', kind: 'intro', eyebrow: 'PARCOURS LOGEMENT', title: 'On va avancer dans le bon ordre.',
        description: 'Tu peux faire ce parcours en plusieurs fois. Tes réponses restent enregistrées sur cet appareil.',
        why: 'Chercher un logement avant de connaître son budget ou de préparer son dossier fait perdre du temps et augmente le risque d’accepter une mauvaise offre.',
        help: ['Tu peux répondre “je ne sais pas” à chaque étape.', 'Les montants saisis servent seulement à préparer une estimation.', 'Aucun document réel n’est envoyé dans cette maquette.'],
      },
      {
        id: 'home-project', kind: 'form', eyebrow: '1 · TON PROJET', title: 'Où et quand veux-tu t’installer ?',
        description: 'Ces informations nous permettent d’adapter le budget, la recherche et le calendrier.',
        why: 'La date d’installation détermine quand demander un garant, préparer le dossier, souscrire une assurance et lancer les démarches après signature.',
        help: ['Une date approximative suffit.', 'Indique la ville principale, même si tu recherches aussi autour.', 'Une colocation peut réduire le loyer mais ajoute des règles de partage.'],
        fields: [
          { id: 'city', label: 'Ville ou zone recherchée', placeholder: 'Ex. Lyon, Lille, Cergy…', hint: 'Tu pourras modifier ce choix plus tard.' },
          { id: 'moveDate', label: 'Date d’installation visée', placeholder: 'Ex. septembre 2026', hint: 'Une estimation suffit.' },
          { id: 'household', label: 'Nombre de personnes dans le logement', placeholder: '1', inputMode: 'numeric' },
          { id: 'housingType', label: 'Type recherché', placeholder: 'Studio, coloc, résidence…' },
        ],
      },
      {
        id: 'home-budget', kind: 'budget', eyebrow: '2 · BUDGET', title: 'Calcule ton vrai budget logement.',
        description: 'On part de ce que tu sais. Tu peux laisser un montant vide et revenir plus tard.',
        why: 'Le loyer affiché n’inclut pas toujours l’énergie, internet, l’assurance, le transport ni la marge nécessaire pour les imprévus.',
        help: ['Utilise des moyennes mensuelles.', 'Ne compte une aide au logement que si tu as déjà une estimation officielle.', 'Le résultat est un plafond de prudence, pas une garantie bancaire.'],
      },
      {
        id: 'home-guarantor', kind: 'single', eyebrow: '3 · GARANTIE', title: 'Quelle est ta situation de garant ?',
        description: 'On préparera ensuite l’option la plus réaliste pour ton dossier.',
        why: 'Beaucoup de bailleurs demandent une garantie. La connaître tôt évite de découvrir le blocage au moment de candidater.',
        help: ['Visale peut être une piste pour certains jeunes.', 'Un garant physique doit généralement fournir ses propres justificatifs.', 'Ne paie jamais un inconnu pour “réserver” une garantie.'],
        options: [
          { id: 'physical', label: 'J’ai un garant physique', caption: 'Parent, proche ou personne de confiance', emoji: '👤' },
          { id: 'visale', label: 'Je veux vérifier Visale', caption: 'Garantie à demander avant la signature du bail', emoji: '🛡️' },
          { id: 'other', label: 'J’ai une autre garantie', caption: 'Organisme, école ou solution privée', emoji: '🏦' },
          { id: 'unknown', label: 'Je ne sais pas encore', caption: 'TutoVie gardera cette étape en attente', emoji: '❔' },
        ],
      },
      {
        id: 'home-file', kind: 'checklist', eyebrow: '4 · DOSSIER', title: 'Prépare ton dossier avant les premières visites.',
        description: 'Coche ce que tu as déjà. Chaque document manquant sera ajouté à ta liste.',
        why: 'Un dossier complet permet de candidater vite sans envoyer au hasard des informations inutiles ou sensibles.',
        help: ['Une copie lisible suffit pour la maquette.', 'Utilise de préférence un service officiel de vérification de dossier.', 'N’envoie pas tes coordonnées bancaires complètes dans une messagerie non sécurisée.'],
        checklist: [
          { id: 'identity', label: "Pièce d'identité", hint: 'Document en cours de validité' },
          { id: 'school', label: 'Certificat de scolarité ou preuve de situation', hint: 'Année en cours' },
          { id: 'resources', label: 'Justificatifs de ressources', hint: 'Bourse, salaire, aide familiale…' },
          { id: 'tax-notice', label: "Avis d'imposition", hint: 'Le tien ou celui du foyer selon ta situation' },
          { id: 'guarantor-file', label: 'Documents du garant', hint: 'Uniquement si tu utilises un garant physique' },
        ],
      },
      {
        id: 'home-search', kind: 'multi', eyebrow: '5 · RECHERCHE', title: 'Choisis tes canaux de recherche.',
        description: 'L’objectif est d’éviter de dépendre d’un seul site et de suivre chaque candidature proprement.',
        why: 'Les offres peuvent être limitées et disparaître vite. Une recherche organisée permet de comparer au lieu de candidater dans l’urgence.',
        help: ['Active des alertes avec ton plafond de budget.', 'Note toujours la date, le contact et le statut de chaque annonce.', 'Vérifie que l’adresse et le loyer sont cohérents avec le secteur.'],
        options: [
          { id: 'crous', label: 'Crous ou résidence étudiante', caption: 'À vérifier selon ton calendrier et ta situation' },
          { id: 'public-platforms', label: 'Plateformes et services publics', caption: 'Offres ou accompagnement institutionnel' },
          { id: 'private-platforms', label: 'Plateformes privées', caption: 'Agences, sites d’annonces et résidences privées' },
          { id: 'network', label: 'École, proches et réseau local', caption: 'Groupes vérifiés et bouche-à-oreille' },
        ],
      },
      {
        id: 'home-ad-check', kind: 'text', eyebrow: '6 · ANNONCE', title: 'Analyse une annonce avant de répondre.',
        description: 'Colle le texte de l’annonce ou résume ce que le propriétaire te demande. L’analyse est simulée dans cette maquette.',
        why: 'Les signaux d’alerte apparaissent souvent dans l’urgence, le paiement demandé, l’absence de visite ou les incohérences du récit.',
        help: ['Ne verse pas d’argent avant d’avoir vérifié le logement et le cadre contractuel.', 'Méfie-toi d’un interlocuteur qui refuse tout échange normal.', 'Conserve les captures et les coordonnées en cas de doute.'],
        placeholder: 'Ex. “Le propriétaire est à l’étranger et demande 600 € avant la visite…”',
      },
      {
        id: 'home-visit', kind: 'checklist', eyebrow: '7 · VISITE', title: 'Prépare la visite et les bonnes questions.',
        description: 'Cette checklist restera accessible pendant la visite sur mobile.',
        why: 'Sous la pression, on oublie facilement les charges, l’état réel, le bruit, le chauffage ou les conditions de départ.',
        help: ['Prends des notes immédiatement.', 'Demande ce qui est inclus dans les charges.', 'Ne confonds pas visite du logement et état des lieux d’entrée.'],
        checklist: [
          { id: 'charges', label: 'Demander le détail des charges' },
          { id: 'energy', label: 'Vérifier chauffage, fenêtres et équipements' },
          { id: 'transport', label: 'Tester le trajet vers le campus' },
          { id: 'contract', label: 'Demander le type de bail et le préavis' },
          { id: 'photos', label: 'Noter les défauts visibles sans photographier sans autorisation' },
        ],
      },
      {
        id: 'home-application', kind: 'upload', eyebrow: '8 · CANDIDATURE', title: 'Prépare un dossier partageable.',
        description: 'La zone de dépôt est factice. Elle montre comment l’application vérifiera les pièces avant création du dossier.',
        why: 'Le but est d’envoyer uniquement les pièces nécessaires, dans un format clair, avec une trace de ce qui a été transmis.',
        help: ['Le futur produit pourra masquer certaines informations.', 'Chaque pièce devra afficher sa date et son statut.', 'Le partage devra pouvoir expirer automatiquement.'],
      },
      {
        id: 'home-lease', kind: 'upload', eyebrow: '9 · BAIL', title: 'Relis le bail avant de signer.',
        description: 'Dépose un exemple de bail pour simuler l’extraction du loyer, des charges, du dépôt, de la durée et du préavis.',
        why: 'Une interface guidée aide à repérer les informations importantes sans prétendre remplacer un conseil juridique.',
        help: ['Compare les montants au contenu de l’annonce.', 'Vérifie l’identité du bailleur et l’adresse.', 'En cas de clause douteuse, demande l’avis d’un organisme compétent.'],
      },
      {
        id: 'home-move-in', kind: 'checklist', eyebrow: '10 · INSTALLATION', title: 'Prépare la remise des clés.',
        description: 'Les étapes sont placées dans l’ordre où elles deviennent utiles.',
        why: 'Certaines démarches sont nécessaires avant les clés, d’autres le jour même ou juste après.',
        help: ['L’assurance habitation doit généralement être prête avant l’entrée.', 'Photographie les compteurs et les défauts dans le cadre de l’état des lieux.', 'Conserve un exemplaire signé de chaque document.'],
        checklist: [
          { id: 'insurance', label: 'Souscrire et télécharger l’assurance habitation' },
          { id: 'inventory', label: 'Faire l’état des lieux avec observations précises' },
          { id: 'meters', label: 'Relever les compteurs et vérifier les contrats' },
          { id: 'keys', label: 'Compter les clés et badges remis' },
          { id: 'evidence', label: 'Conserver photos, bail et état des lieux ensemble' },
        ],
      },
      {
        id: 'home-caf', kind: 'external', eyebrow: '11 · APRÈS L’ENTRÉE', title: 'Prépare ta demande d’aide au logement.',
        description: 'TutoVie ne calcule pas ton droit. Il te prépare à la démarche officielle et suit ce qui manque.',
        why: 'La demande nécessite notamment des informations exactes sur le logement, le bailleur et ton compte bancaire.',
        help: ['Utilise toujours le service officiel.', 'Note la date de demande et les pièces complémentaires demandées.', 'Un changement de situation doit être déclaré auprès de l’organisme concerné.'],
        checklist: [
          { id: 'lease', label: 'Bail ou contrat de résidence disponible' },
          { id: 'rib', label: 'RIB à ton nom disponible' },
          { id: 'landlord', label: 'Coordonnées et informations du bailleur disponibles' },
          { id: 'rent', label: 'Montant exact du loyer et des charges connu' },
        ],
        sourceLabel: 'Ouvrir le site officiel de la CAF',
        sourceUrl: 'https://www.caf.fr/',
      },
      {
        id: 'home-summary', kind: 'summary', eyebrow: 'RÉCAPITULATIF', title: 'Ton plan logement est prêt.',
        description: 'TutoVie rassemble ce que tu sais, ce qui manque et les prochaines actions. Tu peux reprendre n’importe quelle étape.',
        why: 'Le récapitulatif devient ton tableau de suivi jusqu’à l’installation complète.',
        help: ['Relis les réponses avant d’agir.', 'Les sources officielles doivent toujours confirmer les règles applicables.', 'Tu peux exporter ce récapitulatif plus tard quand le backend sera branché.'],
      },
    ],
  },
  {
    id: 'benefits',
    title: 'Mes aides et mes droits',
    shortTitle: 'Aides et droits',
    subtitle: 'Préparer les simulations officielles, les demandes et le suivi des dossiers.',
    icon: '💶',
    outcome: 'À la fin, tu sauras quelles informations préparer, où simuler officiellement et comment suivre chaque demande.',
    estimatedTime: '15 à 25 min',
    recommendedFor: ['benefits'],
    steps: [
      { id: 'benefits-intro', kind: 'intro', eyebrow: 'PARCOURS AIDES', title: 'On ne va pas deviner tes droits.', description: 'TutoVie prépare les informations, t’envoie vers les simulateurs officiels et suit les démarches retenues.', why: 'Une estimation IA non vérifiée peut être trompeuse. Le bon rôle de l’application est de t’orienter et de réduire les oublis.', help: ['Tu peux avancer même si tu ne connais pas tous tes revenus.', 'Le simulateur officiel reste la source de confirmation.', 'Aucune demande n’est réellement transmise dans la maquette.'] },
      { id: 'benefits-profile', kind: 'form', eyebrow: '1 · SITUATION', title: 'Décris ta situation actuelle.', description: 'Quelques informations suffisent pour préparer les bonnes questions.', why: 'Les aides dépendent souvent de l’âge, du statut, du logement, des ressources et parfois du foyer familial.', help: ['Utilise ta situation actuelle, pas celle de l’année dernière.', 'Une estimation est acceptable.', 'Tu pourras corriger les réponses.'], fields: [
        { id: 'studyStatus', label: 'Formation ou statut', placeholder: 'Licence, BTS, école, année de césure…' },
        { id: 'familyStatus', label: 'Situation familiale', placeholder: 'Seul·e, en couple, enfant…' },
        { id: 'nationalityStatus', label: 'Situation de séjour si nécessaire', placeholder: 'Français·e, UE, titre de séjour…' },
      ] },
      { id: 'benefits-income', kind: 'form', eyebrow: '2 · RESSOURCES', title: 'Quelles ressources connais-tu ?', description: 'Indique des moyennes mensuelles ou “je ne sais pas”.', why: 'Les ressources sont l’une des informations les plus souvent demandées lors d’une simulation.', help: ['Sépare bourse, salaire et aide familiale.', 'Ne compte pas deux fois la même somme.', 'Garde les justificatifs associés.'], fields: [
        { id: 'scholarship', label: 'Bourse mensuelle moyenne', placeholder: '0', inputMode: 'numeric', suffix: '€' },
        { id: 'salary', label: 'Salaire ou revenu étudiant moyen', placeholder: '0', inputMode: 'numeric', suffix: '€' },
        { id: 'familySupport', label: 'Aide familiale régulière', placeholder: '0', inputMode: 'numeric', suffix: '€' },
        { id: 'otherIncome', label: 'Autres ressources', placeholder: '0', inputMode: 'numeric', suffix: '€' },
      ] },
      { id: 'benefits-housing', kind: 'single', eyebrow: '3 · LOGEMENT', title: 'Quelle situation logement faut-il simuler ?', description: 'Choisis celle qui correspond au moment où tu feras la demande.', why: 'Le type de logement et le contrat peuvent modifier les démarches à vérifier.', help: ['Si tu cherches encore, choisis “pas encore installé”.', 'Une résidence peut avoir un fonctionnement spécifique.', 'La simulation devra être refaite si la situation change.'], options: [
        { id: 'not-installed', label: 'Je ne suis pas encore installé·e', caption: 'Je prépare le budget et les démarches' },
        { id: 'private', label: 'Location ou colocation privée', caption: 'Bail avec un propriétaire ou une agence' },
        { id: 'residence', label: 'Résidence étudiante', caption: 'Crous, foyer ou résidence privée' },
        { id: 'hosted', label: 'Hébergé·e gratuitement', caption: 'Chez un proche ou la famille' },
      ] },
      { id: 'benefits-docs', kind: 'checklist', eyebrow: '4 · PIÈCES', title: 'Prépare ce qui sera souvent demandé.', description: 'Ce n’est pas une liste universelle, mais une base de préparation.', why: 'Avoir les informations sous la main évite d’abandonner une simulation ou une demande en cours.', help: ['Ne téléverse rien de réel dans la maquette.', 'Les organismes peuvent demander des pièces différentes.', 'Garde la date des documents.'], checklist: [
        { id: 'identity', label: "Pièce d'identité ou titre de séjour" },
        { id: 'rib', label: 'RIB à ton nom' },
        { id: 'resources', label: 'Justificatifs de ressources' },
        { id: 'housing', label: 'Informations sur le logement si tu en as un' },
        { id: 'tax', label: 'Informations fiscales du foyer si demandées' },
      ] },
      { id: 'benefits-simulator', kind: 'external', eyebrow: '5 · SIMULATION OFFICIELLE', title: 'Lance une simulation officielle.', description: 'Le bouton ouvre la source officielle. Tu reviendras ensuite noter les pistes obtenues.', why: 'L’application ne doit pas présenter une estimation non vérifiée comme un droit acquis.', help: ['Prépare tes réponses avant d’ouvrir le simulateur.', 'Prends une capture ou note le résultat.', 'Une simulation ne remplace pas la décision de l’organisme.'], sourceLabel: 'Ouvrir Mes droits sociaux', sourceUrl: 'https://www.mesdroitssociaux.gouv.fr/' },
      { id: 'benefits-results', kind: 'multi', eyebrow: '6 · RÉSULTATS', title: 'Quelles pistes veux-tu suivre ?', description: 'Choisis uniquement les dispositifs que tu souhaites vérifier ou demander.', why: 'Le but est de transformer une longue liste de résultats en actions suivies.', help: ['“Potentiellement éligible” ne signifie pas “accepté”.', 'Chaque organisme doit confirmer.', 'Tu pourras ajouter une autre aide plus tard.'], options: [
        { id: 'housing-aid', label: 'Aide au logement', caption: 'À vérifier après installation selon la situation' },
        { id: 'scholarship', label: 'Bourse ou aide liée aux études', caption: 'À suivre selon le calendrier étudiant' },
        { id: 'mobility', label: 'Aide à la mobilité', caption: 'Déménagement, transport ou changement de région' },
        { id: 'local', label: 'Aide locale', caption: 'Ville, région, établissement ou association' },
        { id: 'emergency', label: 'Aide ponctuelle ou urgence', caption: 'À orienter rapidement vers un interlocuteur humain' },
      ] },
      { id: 'benefits-tracker', kind: 'checklist', eyebrow: '7 · SUIVI', title: 'Prépare le suivi de chaque demande.', description: 'La future version créera une fiche par organisme. Ici, tu testes la logique.', why: 'Une demande peut rester bloquée faute de pièce, de message lu ou de relance au bon endroit.', help: ['Note la date de dépôt.', 'Conserve le numéro de dossier.', 'Vérifie les messages sur l’espace officiel.'], checklist: [
        { id: 'submitted', label: 'Date de dépôt notée' },
        { id: 'reference', label: 'Numéro de dossier conservé' },
        { id: 'messages', label: 'Messages et pièces complémentaires suivis' },
        { id: 'renewal', label: 'Date de renouvellement ou de révision notée' },
      ] },
      { id: 'benefits-summary', kind: 'summary', eyebrow: 'RÉCAPITULATIF', title: 'Ton plan d’aides est prêt.', description: 'Tu peux revenir sur les ressources, le simulateur et le suivi sans tout recommencer.', why: 'Le plan conserve la différence entre une piste, une demande envoyée et un droit confirmé.', help: ['Ne présente jamais une simulation comme une décision.', 'Mets à jour le parcours après un déménagement ou un changement de revenu.', 'Demande de l’aide humaine si la situation est urgente.'] },
    ],
  },
  {
    id: 'documents',
    title: 'Mes documents essentiels',
    shortTitle: 'Documents',
    subtitle: 'Comprendre chaque papier, savoir où le trouver et repérer ce qui manque.',
    icon: '📁',
    outcome: 'À la fin, tu auras un inventaire clair des documents indispensables et une méthode pour les ranger.',
    estimatedTime: '15 à 20 min',
    recommendedFor: ['documents'],
    steps: [
      { id: 'docs-intro', kind: 'intro', eyebrow: 'PARCOURS DOCUMENTS', title: 'On commence par les bases.', description: 'L’objectif n’est pas de tout stocker tout de suite, mais de savoir ce que chaque document signifie.', why: 'Un jeune adulte se retrouve souvent bloqué non parce qu’il est inéligible, mais parce qu’il ne sait pas quel document est demandé ni où le récupérer.', help: ['Tu peux marquer un document “à retrouver”.', 'La zone de stockage reste factice.', 'Les futurs fichiers devront être chiffrés et supprimables.'] },
      { id: 'docs-identity', kind: 'checklist', eyebrow: '1 · IDENTITÉ ET ÉTUDES', title: 'Vérifie tes documents de base.', description: 'Coche ce que tu peux retrouver aujourd’hui.', why: 'Ces documents servent de point de départ dans la plupart des dossiers.', help: ['Vérifie la date de validité.', 'Une photo floue n’est pas une copie exploitable.', 'Le certificat de scolarité change chaque année.'], checklist: [
        { id: 'identity', label: "Pièce d'identité en cours de validité" },
        { id: 'school', label: 'Certificat de scolarité de l’année' },
        { id: 'address-proof', label: 'Justificatif de domicile ou attestation d’hébergement' },
      ] },
      { id: 'docs-bank', kind: 'checklist', eyebrow: '2 · BANQUE ET RESSOURCES', title: 'Prépare les documents liés à l’argent.', description: 'Ils seront demandés pour les virements, aides, logement ou remboursements.', why: 'Un RIB qui n’est pas à ton nom ou un justificatif incomplet peut bloquer une démarche.', help: ['Télécharge le RIB depuis une source bancaire fiable.', 'Conserve les fiches de paie et notifications de bourse.', 'Évite d’envoyer un relevé bancaire complet si ce n’est pas demandé.'], checklist: [
        { id: 'rib', label: 'RIB à ton nom' },
        { id: 'resources', label: 'Justificatifs de ressources récents' },
        { id: 'scholarship', label: 'Notification de bourse si concerné·e' },
      ] },
      { id: 'docs-housing', kind: 'checklist', eyebrow: '3 · LOGEMENT', title: 'Regroupe les preuves liées au logement.', description: 'Ces pièces servent pendant la recherche, l’entrée et la sortie.', why: 'La chronologie des documents peut être utile en cas de litige ou de dépôt de garantie contesté.', help: ['Conserve les versions signées.', 'Ajoute les photos d’état des lieux avec leur date.', 'Garde les échanges importants avec le bailleur.'], checklist: [
        { id: 'lease', label: 'Bail ou contrat de résidence' },
        { id: 'insurance', label: "Attestation d'assurance habitation" },
        { id: 'inventory', label: 'État des lieux d’entrée' },
        { id: 'rent-receipts', label: 'Quittances ou preuves de paiement' },
      ] },
      { id: 'docs-health-tax', kind: 'checklist', eyebrow: '4 · SANTÉ ET IMPÔTS', title: 'Vérifie les documents moins visibles.', description: 'Ils deviennent importants au moment où tu en as besoin, donc mieux vaut les repérer avant.', why: 'Une attestation de droits ou un numéro fiscal peut être difficile à retrouver dans l’urgence.', help: ['Le compte Ameli donne accès à l’attestation de droits.', 'L’avis d’imposition peut appartenir au foyer parental selon la situation.', 'Ne mélange pas numéro fiscal et numéro de sécurité sociale.'], checklist: [
        { id: 'vitale', label: 'Carte Vitale ou attestation de droits' },
        { id: 'mutual', label: 'Attestation de mutuelle si concerné·e' },
        { id: 'tax-notice', label: "Avis d'imposition ou informations du foyer fiscal" },
        { id: 'tax-id', label: 'Numéro fiscal si tu en as un' },
      ] },
      { id: 'docs-upload', kind: 'upload', eyebrow: '5 · COFFRE', title: 'Simule l’ajout d’un document.', description: 'La future interface vérifiera le type, la lisibilité, la date et le propriétaire du document.', why: 'Le coffre doit aider à comprendre le fichier, pas seulement accumuler des PDF.', help: ['Le prototype ne téléverse rien.', 'La version réelle devra chiffrer les documents.', 'Chaque document devra pouvoir être supprimé immédiatement.'] },
      { id: 'docs-naming', kind: 'form', eyebrow: '6 · ORGANISATION', title: 'Choisis une méthode simple de rangement.', description: 'TutoVie peut générer des noms cohérents et des rappels de renouvellement.', why: 'Un fichier nommé “scan0004.pdf” sera difficile à retrouver six mois plus tard.', help: ['Utilise document + année + personne.', 'Évite d’inclure des données très sensibles dans le nom du fichier.', 'Garde une copie hors ligne des documents essentiels.'], fields: [
        { id: 'folderName', label: 'Nom de ton dossier principal', placeholder: 'Ex. Documents administratifs' },
        { id: 'backupPlace', label: 'Où gardes-tu une copie de secours ?', placeholder: 'Ex. disque chiffré, espace cloud personnel…' },
      ] },
      { id: 'docs-summary', kind: 'summary', eyebrow: 'RÉCAPITULATIF', title: 'Ton inventaire documentaire est prêt.', description: 'La vue Documents affichera désormais ce que tu as, ce qui manque et où le récupérer.', why: 'Cet inventaire sert de base à tous les autres parcours.', help: ['Actualise-le à chaque rentrée ou déménagement.', 'Ne conserve pas des documents sensibles sans nécessité.', 'Vérifie toujours la source avant de transmettre une pièce.'] },
    ],
  },
  {
    id: 'health',
    title: 'Ma santé administrative',
    shortTitle: 'Santé',
    subtitle: 'Mettre au clair Ameli, carte Vitale, médecin, mutuelle et remboursements.',
    icon: '🩺',
    outcome: 'À la fin, tu sauras où vérifier ta couverture et qui contacter en cas de problème administratif de santé.',
    estimatedTime: '12 à 18 min',
    recommendedFor: ['health'],
    steps: [
      { id: 'health-intro', kind: 'intro', eyebrow: 'PARCOURS SANTÉ', title: 'On s’occupe uniquement de l’administratif.', description: 'TutoVie ne donne aucun diagnostic. Il t’aide à vérifier les comptes, documents et interlocuteurs.', why: 'Une adresse, un RIB ou une couverture mal renseignée peut ralentir les remboursements.', help: ['Pour une urgence médicale, utilise les services d’urgence appropriés.', 'La maquette ne traite aucune donnée de santé.', 'Les règles doivent être confirmées sur Ameli ou auprès d’un professionnel.'] },
      { id: 'health-ameli', kind: 'single', eyebrow: '1 · COMPTE AMELI', title: 'Peux-tu accéder à ton compte Ameli ?', description: 'Choisis la situation la plus proche.', why: 'Le compte permet de vérifier les remboursements, coordonnées et attestations.', help: ['Ne partage jamais ton mot de passe.', 'En cas de blocage, passe par les contacts officiels.', 'Un compte existant peut nécessiter une mise à jour.'], options: [
        { id: 'yes', label: 'Oui, je peux me connecter' },
        { id: 'no-account', label: 'Je ne pense pas avoir de compte' },
        { id: 'blocked', label: 'Mon accès est bloqué' },
        { id: 'unknown', label: 'Je ne sais pas' },
      ] },
      { id: 'health-details', kind: 'checklist', eyebrow: '2 · INFORMATIONS', title: 'Vérifie les éléments essentiels.', description: 'Coche uniquement ce que tu as réellement contrôlé.', why: 'Des coordonnées à jour facilitent les échanges et les remboursements.', help: ['Vérifie l’adresse actuelle.', 'Contrôle le RIB de remboursement.', 'Télécharge une attestation de droits récente.'], checklist: [
        { id: 'address', label: 'Adresse postale correcte' },
        { id: 'rib', label: 'RIB de remboursement correct' },
        { id: 'rights', label: 'Attestation de droits accessible' },
        { id: 'vitale', label: 'Carte Vitale disponible et à jour' },
      ] },
      { id: 'health-doctor', kind: 'single', eyebrow: '3 · MÉDECIN TRAITANT', title: 'As-tu un médecin traitant déclaré ?', description: 'La future version pourra préparer la démarche ou la question à poser.', why: 'Le parcours de soins et les remboursements peuvent dépendre de cette déclaration.', help: ['Un médecin doit accepter cette déclaration.', 'Tu peux demander une confirmation à l’Assurance Maladie.', 'Ne choisis pas un professionnel sans l’avoir consulté.'], options: [
        { id: 'yes', label: 'Oui' }, { id: 'no', label: 'Non' }, { id: 'unknown', label: 'Je ne sais pas' },
      ] },
      { id: 'health-mutual', kind: 'single', eyebrow: '4 · MUTUELLE', title: 'Quelle est ta couverture complémentaire ?', description: 'Cette étape sert à comprendre qui rembourse quoi.', why: 'La mutuelle, lorsqu’elle existe, intervient en complément de l’Assurance Maladie.', help: ['Tu peux être couvert·e par un contrat familial.', 'Vérifie la date de fin de couverture.', 'Compare les garanties avant toute souscription.'], options: [
        { id: 'family', label: 'Mutuelle familiale' },
        { id: 'personal', label: 'Mon propre contrat' },
        { id: 'employer', label: 'Contrat employeur' },
        { id: 'none', label: 'Aucune ou je ne sais pas' },
      ] },
      { id: 'health-refund', kind: 'external', eyebrow: '5 · REMBOURSEMENTS', title: 'Repère où suivre un remboursement.', description: 'Le bouton ouvre la source officielle. Dans la version réelle, TutoVie affichera seulement un raccourci et un statut saisi par toi.', why: 'Les délais et pièces manquantes doivent être vérifiés dans l’espace officiel.', help: ['Ne communique pas de données de santé au chatbot.', 'Conserve les factures ou feuilles de soins nécessaires.', 'Contacte l’organisme si le remboursement reste incompris.'], sourceLabel: 'Ouvrir Ameli', sourceUrl: 'https://www.ameli.fr/' },
      { id: 'health-contacts', kind: 'form', eyebrow: '6 · CONTACTS', title: 'Prépare tes contacts utiles.', description: 'Tu peux noter uniquement des intitulés dans la maquette.', why: 'Savoir qui appeler évite de chercher dans l’urgence.', help: ['Ajoute ton centre de santé ou médecin habituel.', 'Garde un contact de confiance.', 'Pour une urgence médicale, utilise les numéros d’urgence officiels.'], fields: [
        { id: 'doctorContact', label: 'Médecin ou centre de santé', placeholder: 'Nom ou établissement' },
        { id: 'mutualContact', label: 'Mutuelle ou organisme', placeholder: 'Nom de l’organisme' },
        { id: 'trustedContact', label: 'Contact de confiance', placeholder: 'Prénom uniquement dans la maquette' },
      ] },
      { id: 'health-summary', kind: 'summary', eyebrow: 'RÉCAPITULATIF', title: 'Ton administratif santé est structuré.', description: 'Tu peux revoir chaque point sans saisir de données médicales.', why: 'Le parcours sépare clairement assurance maladie, mutuelle, médecin et urgence.', help: ['Mets à jour les coordonnées après un déménagement.', 'Contrôle régulièrement les remboursements.', 'Demande une aide humaine pour tout problème complexe.'] },
    ],
  },
  {
    id: 'taxes',
    title: 'Mes premiers impôts',
    shortTitle: 'Premiers impôts',
    subtitle: 'Comprendre le foyer fiscal, le numéro fiscal, les revenus et la première déclaration.',
    icon: '🧾',
    outcome: 'À la fin, tu connaîtras les questions à clarifier avant la campagne déclarative et les documents à conserver.',
    estimatedTime: '12 à 18 min',
    recommendedFor: ['taxes'],
    steps: [
      { id: 'tax-intro', kind: 'intro', eyebrow: 'PARCOURS IMPÔTS', title: 'On traduit le vocabulaire avant de remplir quoi que ce soit.', description: 'Cette maquette prépare la démarche mais ne produit pas de déclaration fiscale.', why: 'La difficulté vient souvent de la différence entre rattachement, foyer fiscal, numéro fiscal et revenus à déclarer.', help: ['Les règles peuvent changer.', 'Utilise le service officiel pendant la campagne.', 'En cas de doute, contacte l’administration fiscale.'] },
      { id: 'tax-attachment', kind: 'single', eyebrow: '1 · FOYER FISCAL', title: 'Sais-tu si tu es rattaché·e au foyer de tes parents ?', description: 'Si tu ne sais pas, le parcours préparera la discussion et les vérifications.', why: 'Cette situation influence la manière dont les revenus sont déclarés.', help: ['Ne décide pas seul·e sans vérifier les conséquences pour le foyer.', 'La situation doit être confirmée pour l’année concernée.', '“Habiter ailleurs” ne signifie pas automatiquement “déclarer séparément”.'], options: [
        { id: 'attached', label: 'Oui, je suis rattaché·e' },
        { id: 'independent', label: 'Non, je déclare séparément' },
        { id: 'unknown', label: 'Je ne sais pas encore' },
      ] },
      { id: 'tax-number', kind: 'single', eyebrow: '2 · NUMÉRO FISCAL', title: 'As-tu déjà un numéro fiscal personnel ?', description: 'Ne le saisis pas ici. Indique seulement si tu sais où le retrouver.', why: 'Le numéro fiscal est nécessaire pour accéder à certains services fiscaux personnels.', help: ['Ne partage jamais ce numéro dans une conversation publique.', 'Il peut apparaître sur des courriers ou documents fiscaux.', 'L’administration peut expliquer la démarche d’obtention.'], options: [
        { id: 'yes', label: 'Oui, je sais où le trouver' },
        { id: 'maybe', label: 'Peut-être, mais je dois vérifier' },
        { id: 'no', label: 'Non ou je ne sais pas' },
      ] },
      { id: 'tax-income', kind: 'checklist', eyebrow: '3 · REVENUS', title: 'Rassemble les justificatifs de l’année.', description: 'Le but est de ne pas reconstituer douze mois de revenus au dernier moment.', why: 'Les revenus peuvent provenir de plusieurs employeurs ou situations.', help: ['Classe par année civile.', 'Conserve les attestations et fiches de paie.', 'Ne présume pas qu’un revenu est automatiquement exonéré.'], checklist: [
        { id: 'salary', label: 'Fiches de paie ou attestations employeur' },
        { id: 'internship', label: 'Indemnités ou revenus liés aux études si concernés' },
        { id: 'self-employed', label: 'Revenus indépendants si concernés' },
        { id: 'other', label: 'Autres documents fiscaux reçus' },
      ] },
      { id: 'tax-address', kind: 'form', eyebrow: '4 · ADRESSE ET ANNÉE', title: 'Prépare les informations de contexte.', description: 'Ne saisis pas d’adresse complète dans la maquette.', why: 'La déclaration demande de distinguer l’année des revenus et la situation à certaines dates.', help: ['Note seulement la ville dans le prototype.', 'Vérifie la date de référence sur la source officielle.', 'Un déménagement doit être signalé dans les espaces concernés.'], fields: [
        { id: 'taxYear', label: 'Année des revenus à préparer', placeholder: 'Ex. 2025', inputMode: 'numeric' },
        { id: 'januaryCity', label: 'Ville de résidence au 1er janvier', placeholder: 'Ex. Rouen' },
        { id: 'moves', label: 'As-tu déménagé pendant l’année ?', placeholder: 'Oui, non ou je ne sais pas' },
      ] },
      { id: 'tax-official', kind: 'external', eyebrow: '5 · SOURCE OFFICIELLE', title: 'Ouvre la procédure correspondant à ta situation.', description: 'TutoVie conservera seulement le statut “à faire”, “en cours” ou “terminé”.', why: 'La déclaration doit être réalisée sur le service officiel avec les règles de la campagne en cours.', help: ['Vérifie les dates officielles.', 'Relis les montants préremplis.', 'Garde l’accusé ou l’avis généré.'], sourceLabel: 'Ouvrir impots.gouv.fr', sourceUrl: 'https://www.impots.gouv.fr/' },
      { id: 'tax-archive', kind: 'checklist', eyebrow: '6 · APRÈS LA DÉCLARATION', title: 'Conserve les preuves utiles.', description: 'Ces documents seront réutilisés pour le logement ou certaines démarches.', why: 'L’avis d’imposition est demandé bien après la déclaration elle-même.', help: ['Télécharge les documents dans ton espace personnel.', 'Garde une copie sécurisée.', 'Ne partage que ce qui est réellement demandé.'], checklist: [
        { id: 'receipt', label: 'Accusé ou confirmation conservé' },
        { id: 'notice', label: "Avis d'imposition téléchargé lorsqu’il est disponible" },
        { id: 'folder', label: 'Documents classés dans le dossier de la bonne année' },
      ] },
      { id: 'tax-summary', kind: 'summary', eyebrow: 'RÉCAPITULATIF', title: 'Ta première démarche fiscale est préparée.', description: 'Le récapitulatif sépare les points connus des questions à confirmer.', why: 'Tu arrives sur le service officiel avec les documents et le vocabulaire déjà clarifiés.', help: ['Actualise ce parcours chaque année.', 'Ne conserve pas d’identifiants dans TutoVie.', 'Contacte l’administration pour une réponse personnalisée.'] },
    ],
  },
  {
    id: 'moving',
    title: 'Mon déménagement',
    shortTitle: 'Déménagement',
    subtitle: 'Préavis, contrats, changement d’adresse, état des lieux et installation.',
    icon: '📦',
    outcome: 'À la fin, tu auras une chronologie complète avant, pendant et après le déménagement.',
    estimatedTime: '15 à 25 min',
    recommendedFor: ['moving'],
    steps: [
      { id: 'moving-intro', kind: 'intro', eyebrow: 'PARCOURS DÉMÉNAGEMENT', title: 'On organise les démarches autour de deux dates.', description: 'La date de départ et la date d’entrée servent à construire la chronologie.', why: 'Les contrats, le préavis et l’état des lieux n’ont pas tous la même échéance.', help: ['Une date approximative suffit au début.', 'Le parcours fonctionne aussi pour une résidence étudiante.', 'Aucun contrat n’est réellement résilié dans la maquette.'] },
      { id: 'moving-dates', kind: 'form', eyebrow: '1 · CALENDRIER', title: 'Quelles sont tes dates principales ?', description: 'Indique ce que tu sais déjà.', why: 'Ces dates servent à placer les rappels et à éviter une période sans assurance ou énergie.', help: ['Les dates peuvent se chevaucher.', 'Prévois du temps pour le ménage et les clés.', 'Modifie-les dès qu’elles sont confirmées.'], fields: [
        { id: 'leaveDate', label: 'Date de départ prévue', placeholder: 'Ex. 28 août 2026' },
        { id: 'arrivalDate', label: 'Date d’entrée prévue', placeholder: 'Ex. 1 septembre 2026' },
        { id: 'oldCity', label: 'Ville de départ', placeholder: 'Ex. Dijon' },
        { id: 'newCity', label: 'Ville d’arrivée', placeholder: 'Ex. Grenoble' },
      ] },
      { id: 'moving-notice', kind: 'single', eyebrow: '2 · ANCIEN LOGEMENT', title: 'Où en est ton préavis ?', description: 'Le parcours adaptera les étapes de sortie.', why: 'La date et la forme du préavis peuvent avoir des conséquences sur le loyer restant dû.', help: ['Vérifie les règles applicables à ton bail.', 'Conserve une preuve d’envoi.', 'Une résidence peut avoir ses propres modalités.'], options: [
        { id: 'not-needed', label: 'Je quitte le domicile familial' },
        { id: 'not-sent', label: 'Je dois encore envoyer mon préavis' },
        { id: 'sent', label: 'Mon préavis est envoyé' },
        { id: 'unknown', label: 'Je ne sais pas quoi faire' },
      ] },
      { id: 'moving-contracts', kind: 'checklist', eyebrow: '3 · CONTRATS', title: 'Passe en revue les contrats à transférer ou arrêter.', description: 'Coche uniquement après avoir vérifié la date d’effet.', why: 'Un contrat oublié peut continuer à être facturé ou laisser le nouveau logement sans service.', help: ['Ne résilie pas l’assurance trop tôt.', 'Note les références client.', 'Compare transfert et nouvelle souscription.'], checklist: [
        { id: 'insurance', label: 'Assurance habitation' },
        { id: 'energy', label: 'Électricité ou gaz' },
        { id: 'internet', label: 'Internet' },
        { id: 'transport', label: 'Abonnement de transport' },
        { id: 'subscriptions', label: 'Autres abonnements liés à l’adresse' },
      ] },
      { id: 'moving-address', kind: 'checklist', eyebrow: '4 · ADRESSE', title: 'Prépare les organismes à informer.', description: 'La future version ouvrira chaque espace officiel avec une checklist de statut.', why: 'Les courriers, remboursements et dossiers peuvent rester associés à l’ancienne adresse.', help: ['Ne change l’adresse qu’au bon moment.', 'Conserve une liste de ce qui a été mis à jour.', 'Vérifie aussi les établissements et employeurs.'], checklist: [
        { id: 'school', label: 'Établissement ou scolarité' },
        { id: 'caf', label: 'CAF ou organisme d’aide si concerné' },
        { id: 'ameli', label: 'Assurance Maladie' },
        { id: 'tax', label: 'Impôts' },
        { id: 'bank', label: 'Banque et assurances' },
        { id: 'employer', label: 'Employeur si concerné' },
      ] },
      { id: 'moving-exit', kind: 'checklist', eyebrow: '5 · SORTIE', title: 'Prépare l’état des lieux de sortie.', description: 'Cette liste protège surtout contre les oublis de preuves.', why: 'L’état du logement, les compteurs et les clés conditionnent la clôture correcte du dossier.', help: ['Compare avec l’état des lieux d’entrée.', 'Prends des photos datées dans un cadre légitime.', 'Demande un exemplaire signé.'], checklist: [
        { id: 'cleaning', label: 'Ménage et réparations simples vérifiés' },
        { id: 'meters', label: 'Compteurs relevés' },
        { id: 'photos', label: 'Photos de sortie conservées' },
        { id: 'keys', label: 'Toutes les clés et badges rendus' },
        { id: 'signed', label: 'État des lieux signé récupéré' },
      ] },
      { id: 'moving-arrival', kind: 'checklist', eyebrow: '6 · ARRIVÉE', title: 'Sécurise les premières 24 heures.', description: 'Les éléments essentiels doivent être vérifiés avant de ranger les cartons.', why: 'Après l’installation, les défauts et informations initiales sont plus difficiles à reconstituer.', help: ['Vérifie l’assurance avant les clés.', 'Signale rapidement les anomalies selon la procédure adaptée.', 'Conserve les relevés de compteur.'], checklist: [
        { id: 'insurance-proof', label: 'Attestation d’assurance disponible' },
        { id: 'entry-inventory', label: 'État des lieux d’entrée précis' },
        { id: 'entry-photos', label: 'Photos et défauts conservés' },
        { id: 'utilities', label: 'Énergie, eau et internet vérifiés' },
        { id: 'mailbox', label: 'Nom, boîte aux lettres et accès communs vérifiés' },
      ] },
      { id: 'moving-summary', kind: 'summary', eyebrow: 'RÉCAPITULATIF', title: 'Ton déménagement est planifié.', description: 'Tu peux revenir sur chaque bloc à mesure que les dates se confirment.', why: 'La chronologie évite les résiliations trop tôt, les doubles factures et les preuves manquantes.', help: ['Actualise les dates dès qu’elles changent.', 'Garde les confirmations de résiliation.', 'Vérifie les démarches propres à ta résidence.'] },
    ],
  },
  {
    id: 'contact-router',
    title: 'Qui contacter ?',
    shortTitle: 'Qui contacter',
    subtitle: 'Identifier le bon interlocuteur et préparer ce qu’il faut lui expliquer.',
    icon: '🧭',
    outcome: 'À la fin, tu auras un plan de contact, les documents à préparer et une trace de la demande.',
    estimatedTime: '5 à 10 min',
    recommendedFor: [],
    steps: [
      { id: 'contact-intro', kind: 'intro', eyebrow: 'ORIENTATION', title: 'Décris le problème avant de chercher un numéro.', description: 'TutoVie ne remplace pas l’organisme. Il t’aide à formuler la situation et à choisir le bon canal.', why: 'Appeler le mauvais service ou expliquer le problème sans référence peut multiplier les échanges.', help: ['En cas de danger ou d’urgence médicale, utilise les services d’urgence.', 'Ne donne pas de données sensibles à un interlocuteur non vérifié.', 'Conserve une trace des échanges.'] },
      { id: 'contact-topic', kind: 'single', eyebrow: '1 · SUJET', title: 'Quel est le sujet principal ?', description: 'Choisis le problème le plus urgent.', why: 'Le sujet détermine l’organisme, les preuves et le canal à privilégier.', help: ['Un problème peut concerner plusieurs organismes.', 'Commence par celui qui détient le dossier.', 'Tu pourras créer un second parcours ensuite.'], options: [
        { id: 'housing', label: 'Logement ou propriétaire', emoji: '🏠' },
        { id: 'benefit', label: 'Aide ou dossier bloqué', emoji: '💶' },
        { id: 'health', label: 'Carte Vitale ou remboursement', emoji: '🩺' },
        { id: 'school', label: 'Établissement ou inscription', emoji: '🎓' },
        { id: 'tax', label: 'Impôts ou numéro fiscal', emoji: '🧾' },
        { id: 'fraud', label: 'Arnaque ou demande suspecte', emoji: '⚠️' },
      ] },
      { id: 'contact-detail', kind: 'text', eyebrow: '2 · CONTEXTE', title: 'Résume ce qui s’est passé.', description: 'Écris les faits dans l’ordre, sans informations très sensibles.', why: 'Un résumé factuel aide à obtenir une réponse plus précise.', help: ['Date, action faite, réponse reçue, blocage actuel.', 'Évite les mots de passe et numéros complets.', 'Copie le message exact si cela aide.'], placeholder: 'Ex. “J’ai envoyé le document le 12 août. Mon espace indique toujours pièce manquante…”' },
      { id: 'contact-evidence', kind: 'checklist', eyebrow: '3 · PREUVES', title: 'Prépare les références utiles.', description: 'Coche ce que tu pourras retrouver avant de contacter le service.', why: 'Les références et dates évitent de recommencer toute l’explication.', help: ['Masque les données non nécessaires.', 'Garde les captures avec date.', 'Ne modifie pas les documents originaux.'], checklist: [
        { id: 'reference', label: 'Numéro de dossier ou référence' },
        { id: 'dates', label: 'Dates des actions et messages' },
        { id: 'documents', label: 'Documents concernés' },
        { id: 'screenshots', label: 'Captures ou preuves de l’erreur' },
      ] },
      { id: 'contact-channel', kind: 'single', eyebrow: '4 · CANAL', title: 'Comment souhaites-tu contacter le service ?', description: 'Le futur produit proposera le canal officiel approprié.', why: 'Un écrit est utile pour les dossiers complexes, tandis qu’un appel peut clarifier rapidement une question simple.', help: ['Utilise uniquement les coordonnées officielles.', 'Demande une confirmation écrite après un appel important.', 'Note le nom du service et la date.'], options: [
        { id: 'online', label: 'Messagerie de l’espace officiel' },
        { id: 'phone', label: 'Téléphone' },
        { id: 'appointment', label: 'Rendez-vous physique ou visio' },
        { id: 'letter', label: 'Courrier avec preuve d’envoi' },
      ] },
      { id: 'contact-message', kind: 'form', eyebrow: '5 · PRÉPARATION', title: 'Prépare ta demande en trois phrases.', description: 'La future IA pourra reformuler sans inventer de faits.', why: 'Une demande courte et structurée facilite le traitement.', help: ['Phrase 1 : situation.', 'Phrase 2 : ce que tu as déjà fait.', 'Phrase 3 : ce que tu demandes précisément.'], fields: [
        { id: 'situation', label: 'Ma situation', placeholder: 'Je suis étudiant·e et…' },
        { id: 'alreadyDone', label: 'Ce que j’ai déjà fait', placeholder: 'J’ai envoyé / vérifié / appelé…' },
        { id: 'request', label: 'Ce que je demande', placeholder: 'Je souhaite savoir / obtenir / corriger…' },
      ] },
      { id: 'contact-followup', kind: 'checklist', eyebrow: '6 · SUIVI', title: 'Garde une trace après le contact.', description: 'Cette trace évite de perdre le fil si le dossier continue.', why: 'Les démarches administratives impliquent parfois plusieurs échanges.', help: ['Note la date et le canal.', 'Conserve la réponse.', 'Ajoute la prochaine échéance.'], checklist: [
        { id: 'date', label: 'Date et heure du contact notées' },
        { id: 'response', label: 'Réponse ou compte rendu conservé' },
        { id: 'next', label: 'Prochaine action et date notées' },
      ] },
      { id: 'contact-summary', kind: 'summary', eyebrow: 'RÉCAPITULATIF', title: 'Ton plan de contact est prêt.', description: 'Tu sais quoi expliquer, quoi préparer et comment suivre la réponse.', why: 'Le plan reste attaché au sujet pour les relances futures.', help: ['Vérifie l’identité de l’interlocuteur.', 'N’envoie que les documents nécessaires.', 'Escalade vers une aide humaine si la situation reste bloquée.'] },
    ],
  },
];

export const assistantSuggestions = [
  "Je viens de trouver un logement, je fais quoi maintenant ?",
  "Je ne comprends pas le document qu'on me demande.",
  "Je ne sais pas qui contacter pour un dossier bloqué.",
  "Aide-moi à calculer mon vrai budget logement.",
];

export function getJourney(id: string | null | undefined) {
  return journeys.find((journey) => journey.id === id) ?? null;
}
